import = ["/home/jchlu/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[window]
dimensions = { columns = 120, lines = 40  }

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "F11", action = "ToggleFullscreen" }
]
