import = ["/home/jchlu/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[font]
size = 14.0

[font.normal]
family = "GeistMono Nerd Font Mono"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "F11", action = "ToggleFullscreen" }
]
