# Shell variables
# Generated by 'wal'
wallpaper='/home/jchlu/Pictures/science-fiction-digital-art-concept-art-artwork-futuristic-fantasy-art-1660725-wallhere.com.jpg'

# Special
background='#0c0201'
foreground='#eae9e2'
cursor='#eae9e2'

# Colors
color0='#0c0201'
color1='#CA9360'
color2='#5C7395'
color3='#D26096'
color4='#6E90B8'
color5='#A69D9B'
color6='#CAC1B8'
color7='#eae9e2'
color8='#a3a39e'
color9='#CA9360'
color10='#5C7395'
color11='#D26096'
color12='#6E90B8'
color13='#A69D9B'
color14='#CAC1B8'
color15='#eae9e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
