--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jchlu/Pictures/science-fiction-digital-art-concept-art-artwork-futuristic-fantasy-art-1660725-wallhere.com.jpg"

-- Special
background="#0c0201"
foreground="#eae9e2"
cursor="#eae9e2"

-- Colors
color0="#0c0201"
color1="#CA9360"
color2="#5C7395"
color3="#D26096"
color4="#6E90B8"
color5="#A69D9B"
color6="#CAC1B8"
color7="#eae9e2"
color8="#a3a39e"
color9="#CA9360"
color10="#5C7395"
color11="#D26096"
color12="#6E90B8"
color13="#A69D9B"
color14="#CAC1B8"
color15="#eae9e2"
