"Session Management
set sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
source ~/.config/vim/options.vim
source ~/.config/vim/keybinds.vim
source ~/.config/vim/plugins.vim
source ~/.config/vim/colors.vim
